# Generated by Django 3.2.23 on 2024-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0123_sale_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
