# Generated by Django 3.2.23 on 2024-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0127_auto_20240405_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
